### ISSUE TITLE
ModuleNotFoundError: No module named 'dinov2'

### ISSUE THREAD

**Issue by zfkdsg** [IRMVLab/SNI-SLAM#18]
When I ran the code, I encountered the following issue:

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from src.SNI_SLAM import SNI_SLAM
  File "run.py", line 23, in main
    sni_slam = SNI_SLAM(cfg, args)  
  File "/home/dlut/zfk/SNI-SLAM/src/SNI_SLAM.py", line 110, in __init__
    self.model_manager = ModelManager(cfg)
  File "/home/dlut/zfk/SNI-SLAM/src/networks/model_manager.py", line 26, in __init__
    self.cnn = self.get_dinov2().cuda()
  File "/home/dlut/zfk/SNI-SLAM/src/networks/model_manager.py", line 42, in get_dinov2
    model = DINO2SEG(img_h=self.img_h, img_w=self.img_w, num_cls=self.n_classes, edge=self.crop_edge, dim=self.dim)
  File "/home/dlut/zfk/SNI-SLAM/src/networks/dinov2_seg.py", line 60, in __init__
    self.backbone = make_dinov2_model(arch_name="vit_base")
  File "/home/dlut/zfk/SNI-SLAM/src/networks/dinov2_seg.py", line 36, in make_dinov2_model
    from dinov2.models import vision_transformer as vits

ModuleNotFoundError: No module named 'dinov2'

I'm not sure where I made a mistake.

**Comment by zfkdsg** [comment]
I found out that I didn't unzip the folder and the problem has been solved

**Comment by MrCloth** [comment]
Please tell me which folder is the one that cause the problem, I'm stuck in this one too.

**Comment by MrCloth** [comment]
> Please tell me which folder is the one that cause the problem, I'm stuck in this one too.

never mind, just found it in the 'seg' folder, excuse my carelessness
