### ISSUE TITLE
The GPU memory overflowed

### ISSUE THREAD

**Issue by castle1874** [IRMVLab/SNI-SLAM#4]
When I ran the command python -W ignore run.py configs/Replica/room1.yaml, the following error occurred:
c_dim 16
INFO - 2024-09-05 20:10:30,135 - vision_transformer - using MLP layer as FFN
INFO: The output folder is output/Replica/room1/test
INFO: The GT, generated and residual depth/color images can be found under output/Replica/room1/test/tracking_vis/ and output/Replica/room1/test/mapping_vis/
INFO: The mesh can be found under output/Replica/room1/test/mesh/
INFO: The checkpoint can be found under output/Replica/room1/test/ckpt/
Process Process-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/sni/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/sni/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/SNI-SLAM/src/SNI_SLAM.py", line 257, in mapping
    self.mapper.run()
  File "/home/ubuntu/SNI-SLAM/src/Mapper.py", line 474, in run
    sem_feat = self.model_manager.cnn(frame_rgb)  # 占用49MB
  File "/home/ubuntu/anaconda3/envs/sni/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/SNI-SLAM/src/networks/dinov2_seg.py", line 97, in forward
    out = self.backbone.forward_features(x.float())
  File "/home/ubuntu/SNI-SLAM/seg/facebookresearch_dinov2_main/dinov2/models/vision_transformer.py", line 228, in forward_features
    x = blk(x)
  File "/home/ubuntu/anaconda3/envs/sni/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/SNI-SLAM/seg/facebookresearch_dinov2_main/dinov2/layers/block.py", line 247, in forward
    return super().forward(x_or_x_list)
  File "/home/ubuntu/SNI-SLAM/seg/facebookresearch_dinov2_main/dinov2/layers/block.py", line 105, in forward
    x = x + attn_residual_func(x)
  File "/home/ubuntu/SNI-SLAM/seg/facebookresearch_dinov2_main/dinov2/layers/block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
  File "/home/ubuntu/anaconda3/envs/sni/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/SNI-SLAM/seg/facebookresearch_dinov2_main/dinov2/layers/attention.py", line 69, in forward
    return super().forward(x)
  File "/home/ubuntu/SNI-SLAM/seg/facebookresearch_dinov2_main/dinov2/layers/attention.py", line 56, in forward
    attn = attn.softmax(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 764.00 MiB (GPU 0; 5.77 GiB total capacity; 885.98 MiB already allocated; 320.50 MiB free; 906.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

 If i don't want to rely on hardware upgrades, what should i do?

**Comment by zstsandy** [comment]
The error shows that there is insufficient GPU memory. SNI-SLAM requires at least 10GB of GPU memory to run completely.
